services:
  auth:
    build:
      context: ./packages/api
      dockerfile: apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./packages/api/apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules/
      - /app/apps/auth/node_modules/
    develop:
      watch:
        - action: sync
          path: ./packages/api
          target: /app
          ignore:
            - node_modules/
            - .git/
            - dist/
        - action: rebuild
          path: package.json

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      target: development
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules/
    develop:
      watch:
        - action: sync
          path: ./packages/client
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./packages/client/package.json
    environment:
      - VITE_API_URL=http://localhost:3001

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: SGA-dev
